---
title: "Primary endpoint analysis"
output: html_document
date: "2022-12-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(epitools)
library(gtsummary)
getwd()

```

## 



```{r load_data}
sero_outcomes <- read_csv("../data/serology_outcomes.csv")


sero_outcomes$outcome_serology = as.numeric(!is.na(sero_outcomes$outcome))

inclusion_data = readxl::read_excel(path = '../data/Time_events_16_01_2023_REVISED_MM_WS_Latest_FINAL_19_01_23.xlsx') #C:/Academico/Projetos/Cloroquina/Time_events_16_01_2023_REVISED_MM_WS_Latest_FINAL_19_01_23.xlsx'


outcome_dat = merge(inclusion_data[, c('subjectno','treatment','pcr_event', 'age_calyr')], # , 'sex', "anychronic", "comorbidities", "diabetes", "bmi" 
                    sero_outcomes[,c('subjectno','outcome_serology',
                                     'serum_available','dbs_available',
                                     'type_data')],
                    by = 'subjectno', all.x=T)
symptomatic = read_delim('../data/Symptomatic.csv',delim = ';')
outcome_dat = merge(outcome_dat, symptomatic, by='subjectno')

glimpse(outcome_dat)


```



# make endpoints

```{r, echo=F}
outcome_dat$Primary_endpoint = (outcome_dat$outcome_serology==1 | outcome_dat$pcr_event==1) & outcome_dat$symptomatic=='Symptomatic'
writeLines('Primary endpoint (symptomatic COVID-19):')
table(outcome_dat$Primary_endpoint, outcome_dat$treatment)

outcome_dat$Asymptomatic_SARSCoV2 = (outcome_dat$outcome_serology==1 | outcome_dat$pcr_event==1) & outcome_dat$symptomatic=='Asymptomatic'

writeLines('Asymptomatic SARS-CoV-2:')
table(outcome_dat$Asymptomatic_SARSCoV2, outcome_dat$treatment)

writeLines('All PCR confirmed Symptomatic COVID-19:')
table(outcome_dat$pcr_event, outcome_dat$treatment)

writeLines('All serologically confirmed SARS-CoV-2 infections:')
outcome_dat$Serology_COVID19 = outcome_dat$outcome_serology==1 & 
  outcome_dat$symptomatic=='Symptomatic'
table(outcome_dat$Serology_COVID19, outcome_dat$treatment)

writeLines('All Symptomatic COVID-19 serologically confirmed using serum:')

outcome_dat$Serum_COVID19 = outcome_dat$outcome_serology==1 &
  outcome_dat$serum_available==1 &
  outcome_dat$symptomatic=='Symptomatic'
table(outcome_dat$Serum_COVID19, outcome_dat$treatment)

writeLines('All Symptomatic COVID-19 serologically confirmed using DBS:')
outcome_dat$DBS_COVID19 = outcome_dat$outcome_serology==1 &
  outcome_dat$dbs_available==1 & outcome_dat$serum_available==0 &
  outcome_dat$symptomatic=='Symptomatic'
table(outcome_dat$DBS_COVID19, outcome_dat$treatment)
getwd()

write_csv(x = outcome_dat,file = '../data/outcomes_derived.csv')
```

# Risk ratio estimation for primary endpoint
cloroquina$anychronic <- as.factor(cloroquina$anychronic)
cloroquina$comorbidities <- as.factor(cloroquina$comorbidities)
cloroquina$diabetes <- as.factor(cloroquina$diabetes)

```{r}
riskratio(table(outcome_dat$Primary_endpoint, outcome_dat$treatment),rev='rows',method = 'wald')
outcome_dat$treatment <- as.factor(outcome_dat$treatment)
outcome_dat$treatment <- relevel(outcome_dat$treatment, ref = "Placebo")

modelo1 <- glm(Primary_endpoint ~ treatment, data = outcome_dat, family=poisson(link='log'))
summary(modelo1)
tbl_regression(modelo1, exponentiate = T)
mean(outcome_dat$age_calyr)
median(outcome_dat$age_calyr)



```

```{r}
modelo1_b <- glm(Primary_endpoint ~ treatment + age_calyr, data = outcome_dat, family=poisson(link='log'))
tbl_regression(modelo1_b, exponentiate = T)

```


for PCR endpoint

```{r}
model2 <- glm(pcr_event ~ treatment + age_calyr, data = outcome_dat, family=poisson(link='log'))
#summary(model2)
tbl_regression(model2, exponentiate = T)

confint(model2)
# Exponenciar os coeficientes e seus intervalos de confiança
exp(confint(model2))

```
# Calcular o valor de p de fisher

```{r}
# Criar uma tabela de contingência
tabela <- table(outcome_dat$Primary_endpoint, outcome_dat$treatment)
```


```{r}
fisher.test(tabela)
```

```{r}
chisq.test(tabela)
```

